### ISSUE TITLE
Добрый день. Как с вами связаться? Требуются ваши знания разработчика ПО

### ISSUE THREAD

**Issue by Dmitryi93** [PawnsOfBear/CCCNextGen_update#1]
Добрый день. Как с вами связаться? Требуются ваши знания разработчика ПО

**Comment by PawnsOfBear** [comment]
Добрый, adanas69@gmail.com

**Comment by PawnsOfBear** [comment]
> Добрый день. Как с вами связаться? Требуются знания вашего разработчика ПО
Добрый, adanas69@gmail.com
